### ISSUE TITLE
AWS IAM changes single element "Actions" and "Resources" arrays into not arrays.

### ISSUE THREAD

**Issue by matthew-lucidchart** [lucidsoftware/cumulus#125]
Need to compare single vs arrays.

**Comment by mike503** [comment]
when I ran vpc migrate, I get this. Which I think might be similar / related? I have no Ruby fu.

```
cumulus/lib/vpc/manager/Manager.rb:364: warning: wrong element type Fixnum at 0 (expected array)
cumulus/lib/vpc/manager/Manager.rb:364: warning: ignoring wrong elements is deprecated, remove them explicitly
cumulus/lib/vpc/manager/Manager.rb:364: warning: this causes ArgumentError in the next release
```

Perhaps single returns vs. array returns is something that needs to be done globally.

**Comment by msiebert** [comment]
@mike503 That's probably a different issue than what's going on here. Feel free to create an issue for it.
