### ISSUE TITLE
Documentation site CSS does not render on HTTPS connection

### ISSUE THREAD

**Issue by conorgil** [lucidsoftware/cumulus#126]
The CSS on the documentation site is not loading on HTTPS connection because it is mixed content.

![screen shot 2016-05-06 at 5 34 30 pm](https://cloud.githubusercontent.com/assets/945571/15088421/e4e0d400-13b0-11e6-84d7-503bd8bec03d.png)

**Comment by msiebert** [comment]
Fixed!
