### ISSUE TITLE
Everything registers as a diff in SQS

### ISSUE THREAD

**Issue by msiebert** [lucidsoftware/cumulus#146]
This happened either as a result of upping the aws-sdk version or the type changes @mcrossen made. Looks like it's probably comparing ints to strings and `"0" != 0` :(

**Comment by msiebert** [comment]
I think this might have actually been caught by the tests I've got in #141

**Comment by mcrossen** [comment]
k. I'm creating a pull request for this. I've tested the fix, and it works out well. Turns out, the aws sdk is to blame. The sdk is returning the string encoded integers. In the fix, I'm just converting the values back to integers.
