### ISSUE TITLE
scalegroup min/max/desired

### ISSUE THREAD

**Issue by dtorgy** [lucidsoftware/cumulus#57]
When a group has a min/max/desired specified and there are scheduled policies for scaling in place, then it becomes difficult to do a sync because depending on time of day the group may be incorrect.

Cumulus should never specify the desired capacity unless it is outside of the range of min/max.

Cumulus should use the most recent scheduled task min/max when syncing the group unless there are no scheduled tasks set. In which case it should use the min/max from the group.

**Comment by krjackso** [comment]
Fixed in https://github.com/lucidsoftware/cumulus/pull/85
