### ISSUE TITLE
autoscaling diff

### ISSUE THREAD

**Issue by dtorgy** [lucidsoftware/cumulus#86]
Launch configurations can be updated dynamically by other things.

Cumulus should be able to ignore differences for launch configurations.

My vote would be to make a config value of something like:
ignore-launch-config=true/false

and then have a command line option to override the default config value
--ignore-launch-config true/false OR something

That way if you want diffing/syncing on by default you can, if you want it off by default you can.

**Comment by krjackso** [comment]
This is fixed, using the same config value that we use for syncing launch configs "override-launch-config-on-sync"
